name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Enable Corepack and use Yarn
        run: corepack enable && corepack prepare yarn@3.5.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Build package
        if: ${{ success() }}
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.email "quentin.juarez@hotmail.fr"
          git config --global user.name "Quentin Juarez"

      - name: Bump package version (patch)
        run: npm version patch
        env:
          NPM_CONFIG_GIT_TAG_VERSION: "true"

      - name: Push changes
        run: git push --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
